service:
  name: secrets-api

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  stage: testing
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["SecretsDynamoDBTable", "Arn" ] }
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - { "Fn::GetAtt": ["FileStorageBucket", "Arn" ] }
        - { "Fn::Join": [ "/", [ 
            { "Fn::GetAtt": ["FileStorageBucket", "Arn" ] }, "*" 
          ]]}

functions:
  restHandler:
    handler: src/lambda.handler
    events:
      - http: 
          path: /{any+}
          method: ANY
          cors: true
  
resources:
  Resources:
    FileStorageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: securebin-filestorage
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        VersioningConfiguration:
          Status: Suspended
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: [GET, PUT]
              AllowedOrigins: ['*']
              Id: CORSRuleId1
              MaxAge: '3600'
    SecretsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: Secrets
        TimeToLiveSpecification:
          AttributeName: expires
          Enabled: true